### ISSUE TITLE
Messaging system?

### ISSUE THREAD

**Issue by baudren** [seanfisk/ecs#11]
Hi, 

first of all, thanks for the project! It looks already really nice. I was wondering if you had any plans on implementing a messaging system within your framework - or if it is left to the users to implement one?

I am starting to use it alongside libtcod, and it works nicely so far, but I am starting to wish for a way for systems to broadcast messages that would be recovered by other systems, or entities (though I am not completely clear on how it would work...). Anyway, thanks in advance!

**Comment by pmrv** [comment]
If it's just about sending information to systems, you can easily use components for that. I did something like that [here](https://github.com/ponderstibbons/CoPanzers), where I used a [component](https://github.com/ponderstibbons/CoPanzers/blob/master/copanzers/components/destroyed.py)  to tag destroyed entities and have a [system](https://github.com/ponderstibbons/CoPanzers/blob/master/copanzers/systems/killsystem.py) react on that. I don't actually pass arguments along in this example, but it would be easy to expand it in that way. 
And passing messages between entities doesn't make exactly sense, since they're just identifiers.

Can you give a usage example or situation of how this would be used? I'm not sure whether I completely understand what you're looking for.

**Comment by seanfisk** [comment]
@baudren I am going to yield to @ponderstibbons here as I think he has a better understanding of what is needed.

**Comment by baudren** [comment]
thanks @ponderstibbons for the useful example. Indeed, this looks like one way of doing it - instead of passing a message, to use Components as the message.

What I had in mind was a basic system of inventory - where a key press would ask the InventorySystem to start displaying itself. But what you are suggesting is merely to add a component, say, "Active", to the inventory entity, and have the InventorySystem do something only if this component is there.

I will try around with these ideas - the whole thing is still very new to me, and I am still trying to wrap my head around it, so thanks for the tips!

**Comment by pmrv** [comment]
Depending on how you built stuff so far, you could probably even go a
step further and just toggle the component that handles the display of
your inventory (in the example above I called it `Renderable`) with a
key press, without the need for a "dummy" message component.

But that being said, the example above is still the only thing I ever
built with ECS, so I don't want to give the impression as if I had any
authority in these questions. :D

**Comment by baudren** [comment]
Ok, thanks for the info. I guess this can be closed now, but I'll keep an eye out for the project. Cheers!

**Comment by baudren** [comment]
Hi @ponderstibbons,

two things as an update:
- I am less and less convinced that creating a component for each case of communication is a good solution. It will quickly blow up as you add more and more game logic. You mentioned in your program the component `Destroyed` that is then caught by another system. But similarly, you would need a `Damaged`, that stores an value of damage, if you were to implement a slightly more complex interaction. Or a `DamagedPart` that would store both the value and the part of the system... etc. All this will lead to a multiplication of components that are simply empty classes (I am no expert in memory usage, but creating an empty class surely takes more memory than creating a string, for the `Damaged` example).
- I have found a good description of what I have in mind, already implemented in another ECS framework, EntityX, https://github.com/alecthomas/entityx#events-communicating-between-systems
  Where they simply have another type of object, called Events. A system can emit events, that can store anything, from entities to strings, and another system can listen for an event. On receiving the event, you can then perform an action.

For an example where this could be helpful in clearing the logic, imagine a situation where 10 creatures are fighting with each other on a scene. Each blow dealt will remove health points from one creature, and add experience to another.

You would have a system that detects the collision of the weapons, and it knows which creature hit which other creature. How does this system communicates with the one dealing with removing health-point?

You could of course attach to the attacker a component `GainedExp`, that stores the value, and a `LostHealth` to the attacked. But already, if a person is hit twice simultaneously, you will have to check whether the `LostHealth` is already there, and add to its value... And how do you track from which entity the experience was gained? 

With an event system, on the other hand, every time a collision is detected, you can broadcast the relevant information: `(entity1, entity2, {'GainedExp': 10}, {'LostHealth':20})`. If a similar message is broadcast several times, the corresponding listener will simply apply several time the change. The listening system is indeed better suited to deal with this information than the emitting one, which is why you want to simplify the handling of these things as simple messages. You can there keep track easily of which entities did this entity hurt, etc...

I hope my point is slightly clearer now that I had some time to think it through. I think it would be possible to implement this in the framework, but whether or not it would be needed by more people than me, it is not clear yet :)

Cheers!

**Comment by pmrv** [comment]
Thanks for that example. I see what you mean and I'm not against adding such a thing per se, but I am not completely convinced this needs to be done either, so I would still defer this decision to @seanfisk. 

However, I think it would be overkill to use in the examples you mentioned. I think the problem is rather that you coupled systems and components to
tightly. Access to a component does not have to go through only one system.
So in your case instead of having a system, which only decreases health on
request of other systems, just have those systems fetch the `Health` component
and do the decreasing themselves. So if you look into my example project above,
you'll find that while I have [`HealthSystem`](https://github.com/ponderstibbons/CoPanzers/blob/master/copanzers/systems/healthsystem.py), all it ever does is checking
whether an entity has negative or zero health and if so destroys it. All access
to the hitpoints of entities is done directly in other system, e.g.
[`CollisionSystem`](https://github.com/ponderstibbons/CoPanzers/blob/master/copanzers/systems/collisionsystem.py).

If you had a separate system before to enforce certain access restrictions on
component members, you can always emulate that effect via python properties.
